headersOrigin = "config"
redirectsOrigin = "config"
functionsDirectory = "/Users/gxjansen/Documents/GitHub/llama/llama-wool-farm/netlify/functions"
functionsDirectoryOrigin = "config-v1"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-lighthouse"

[plugins.inputs]

[plugins.inputs.thresholds]
performance = 0.9
accessibility = 0.9
best-practices = 0.9
seo = 0.9
pwa = 0.9

[build]
publish = "/Users/gxjansen/Documents/GitHub/llama/llama-wool-farm/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/gxjansen/Documents/GitHub/llama/llama-wool-farm/netlify/functions"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/service-worker.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]
Role = ["admin", "user"]

[redirects.headers]